### ISSUE TITLE
NegatedCondition should override ToString()

### ISSUE THREAD

**Issue by Anlo2846** [JohanLarsson/Gu.Reactive#10]
When viewing a condition tree in the debugger, NegatedCondition does not use the {Name: MyCondition, IsSatisfied: false} format of Condition but only shows {NegatedCondition}.

/Andreas

**Comment by JohanLarsson** [comment]
How do we want it formatted?
`Negated_{ConditionName} IsSatisfied:true`

**Comment by Anlo2846** [comment]
I suggest using the same formatting as Condition:

public override string ToString() => $"Name: {(string.IsNullOrEmpty(this.Name) ? this.GetType() .PrettyName() : this.Name)}, IsSatisfied: {this.IsSatisfied?.ToString() ?? "null"}";
